### ISSUE TITLE
建议加入新题目

### ISSUE THREAD

**Issue by ZHYX3423** [Dream-XJ/Information-Technology-Homework#1]
2023年5月1日是星期一，请输入该年份5月的任意一天日期，输出该天是星期几。例如：输入1，输出1；输入17，输出3。如果该天是星期日，则输出7。

**Comment by Dream-XJ** [comment]
你说得对，但是北京三班高一四中是由李博怡自主研发的.....

**Comment by Dream-XJ** [comment]
最新的题目已经push.
